### ISSUE TITLE
Build failure with Golang 1.13

### ISSUE THREAD

**Issue by eclipseo** [go-openapi/validate#113]
Issue appearing on Golang 1.13 beta 1 on Fedora Rawhide:

```
Testing    in: /builddir/build/BUILD/validate-0.19.0/_build/src
         PATH: /builddir/build/BUILD/validate-0.19.0/_build/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
       GOPATH: /builddir/build/BUILD/validate-0.19.0/_build:/usr/share/gocode
  GO111MODULE: off
      command: go test -buildmode pie -compiler gc -ldflags "-X github.com/go-openapi/validate/version=0.19.0 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '"
      testing: github.com/go-openapi/validate
github.com/go-openapi/validate
--- FAIL: Test_Issue1614 (0.24s)
panic: Invalid schema provided to SchemaValidator: object has no key "default" [recovered]
	panic: Invalid schema provided to SchemaValidator: object has no key "default"
goroutine 106 [running]:
testing.tRunner.func1(0xc00028eb00)
	/usr/lib/golang/src/testing/testing.go:874 +0x3a5
panic(0x559da316d720, 0xc0009d80f0)
	/usr/lib/golang/src/runtime/panic.go:663 +0x1b6
github.com/go-openapi/validate.NewSchemaValidator(0xc000669440, 0x559da3212b00, 0xc000669440, 0x0, 0x0, 0x559da32353a0, 0xc00032a6c0, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/validate-0.19.0/_build/src/github.com/go-openapi/validate/schema.go:72 +0x102a
github.com/go-openapi/validate.(*SpecValidator).Validate(0xc0001e5200, 0x559da31e4960, 0xc00061b360, 0xc000a70bb0, 0xc000a70c60)
	/builddir/build/BUILD/validate-0.19.0/_build/src/github.com/go-openapi/validate/spec.go:92 +0x218
github.com/go-openapi/validate.testIssue(0xc00028eb00, 0xc0001af100, 0x1d, 0x0, 0x3)
	/builddir/build/BUILD/validate-0.19.0/_build/src/github.com/go-openapi/validate/messages_test.go:454 +0x1e1
github.com/go-openapi/validate.Test_Issue1614(0xc00028eb00)
	/builddir/build/BUILD/validate-0.19.0/_build/src/github.com/go-openapi/validate/messages_test.go:476 +0xe2
testing.tRunner(0xc00028eb00, 0x559da321ba40)
	/usr/lib/golang/src/testing/testing.go:909 +0xcb
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:960 +0x352
exit status 2
FAIL	github.com/go-openapi/validate	2.846s
```

**Comment by eclipseo** [comment]
Fixed in https://github.com/go-openapi/jsonpointer/commit/a67b0cdac37a3489417baf74a7c7802673395a2d
