### ISSUE TITLE
validation fails for a valid spec

### ISSUE THREAD

**Issue by jbub** [go-openapi/validate#17]
I am trying to validate this spec:
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore-separate/spec/swagger.yaml
## Using go swagger:

```
swagger version
version: 0.7.2
commit: f56b02a7f80ed9ec54fee277ec7a57de1e329f79
```

```
swagger validate swagger.yaml
```
## Fails with:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe1ee7]

goroutine 1 [running]:
panic(0x689080, 0xc420014090)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/spec.expandSchema(0x0, 0x0, 0x0, 0xc420284600, 0x0, 0x0, 0x0, 0x100, 0x0, 0x0, ...)
    /go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/spec/expander.go:446 +0x3e7
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/spec.expandItems(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/spec/expander.go:405 +0x2cf
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/spec.expandSchema(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/spec/expander.go:449 +0x58e
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/spec.expandResponse(0xc42097a910, 0xc4204730c0, 0xc42055e8a0, 0x0)
    /go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/spec/expander.go:602 +0x1ff
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/spec.expandOperation(0xc420105a40, 0xc4204730c0, 0x0, 0xc42055ef70)
    /go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/spec/expander.go:575 +0x31b
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/spec.expandPathItem(0xc42020c800, 0xc4204730c0, 0xc42055ef70, 0xadde40)
    /go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/spec/expander.go:534 +0x14e
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/spec.ExpandSpec(0xc420344900, 0xde5, 0x1023)
    /go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/spec/expander.go:351 +0x7a1
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/loads.(*Document).Expanded(0xc4207679c0, 0xc420891901, 0x3, 0x4)
    /go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/loads/spec.go:140 +0x91
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate.(*SpecValidator).validateReferencesValid(0xc42055fac8, 0xc42073eb60)
    /go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate/spec.go:614 +0x181
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate.(*SpecValidator).Validate(0xc42055fac8, 0x6eb3e0, 0xc4207679c0, 0x1023, 0x734f36)
    /go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate/spec.go:113 +0x2a4
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate.Spec(0xc4207679c0, 0xae5300, 0xc420474d20, 0x0, 0x0)
    /go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate/spec.go:50 +0x81
github.com/go-swagger/go-swagger/cmd/swagger/commands.(*ValidateSpec).Execute(0xb4baf0, 0xc4203123e0, 0x1, 0x2, 0x1, 0x2)
    /go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/validate.go:46 +0xbe
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc4203a4d20, 0xc4200780a0, 0x2, 0x2, 0x8, 0x4, 0xc420098b40, 0xc4202be800, 0xc4202f7e48)
    /go/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:315 +0x8e6
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc4203a4d20, 0x6, 0x737738, 0x6, 0x1, 0x77c2b1)
    /go/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:185 +0x74
main.main()
    /go/src/github.com/go-swagger/go-swagger/cmd/swagger/swagger.go:90 +0x455
```
## Using swagger tools:

```
swagger-tools --version
0.10.1
```

```
swagger-tools validate -v swagger.yaml
```
## Succeeds with:

```
Validation Details:

  Swagger Version: 2.0
  Swagger file: swagger.yaml

Swagger document is valid
```

**Comment by jbub** [comment]
problem caused by invalid homebrew installation, closing

**Comment by casualjim** [comment]
```
git:(master) » swagger validate ./swagger.yaml
The swagger spec at "./swagger.yaml" is invalid against swagger specification 2.0. see errors :
- child url is nil
```
