### ISSUE TITLE
go-swagger and additionalProperties generates panic

### ISSUE THREAD

**Issue by lestrrat** [go-openapi/validate#26]
I got this panic by using `additionalProperties` in one of the response definitions.
(I guessed that this issue blongs to go-openapi instead of go-swagger, let me know if I'm wrong)

```
$ % swagger generate server  
panic: interface conversion: interface {} is spec.Schema, not spec.Response

goroutine 1 [running]:
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate.(*SpecValidator).validateResponseExample(0xc421ea7958, 0xc42046d8a0, 0x8, 0xc421ea76a8, 0x0)
	/Users/daisuke/dev/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate/spec.go:645 +0x2e6
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate.(*SpecValidator).validateExamplesValidAgainstSchema(0xc421ea7958, 0xc4203a6300)
	/Users/daisuke/dev/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate/spec.go:671 +0x25d
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate.(*SpecValidator).Validate(0xc421ea7958, 0x17619a0, 0xc420721c20, 0x1322b44, 0x16f1360)
	/Users/daisuke/dev/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate/spec.go:125 +0x37b
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate.Spec(0xc420721c20, 0x1b7ef80, 0xc420373b00, 0x0, 0x0)
	/Users/daisuke/dev/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate/spec.go:51 +0x81
github.com/go-swagger/go-swagger/generator.validateSpec(0x17baa07, 0xc, 0xc420721c20, 0xc, 0xc420721c20)
	/Users/daisuke/dev/src/github.com/go-swagger/go-swagger/generator/shared.go:607 +0x86
github.com/go-swagger/go-swagger/generator.newAppGenerator(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420162380, 0x1583cba, ...)
	/Users/daisuke/dev/src/github.com/go-swagger/go-swagger/generator/support.go:80 +0xae4
github.com/go-swagger/go-swagger/generator.GenerateServer(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420162380, 0xc4204c9c98, ...)
	/Users/daisuke/dev/src/github.com/go-swagger/go-swagger/generator/support.go:39 +0x94
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Server).Execute(0xc420822b40, 0xc420848200, 0x0, 0x2, 0xc420822b40, 0x1)
	/Users/daisuke/dev/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/server.go:102 +0x4e9
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc420812a80, 0xc420010160, 0x2, 0x2, 0x1010f88, 0x30, 0xc420246900, 0xc420427980, 0xc4204272c8)
	/Users/daisuke/dev/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:316 +0x893
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc420812a80, 0x6, 0x17b15d2, 0x6, 0x0, 0x17f9437)
	/Users/daisuke/dev/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x73
main.main()
	/Users/daisuke/dev/src/github.com/go-swagger/go-swagger/cmd/swagger/swagger.go:105 +0x858
```

```yaml
swagger: '2.0'
info:
  description: Example API service
  version: 1.0.0
  title: Example API
host: localhost
basePath: /v1
tags:
  - name: example
    description: Example API
schemes:
  - http
paths:
  '/example':
    get:
      tags:
        - example
      summary: summary
      description: description
      operationId: example
      produces:
        - application/json
      responses:
        '200':
          $ref: '#/definitions/Example'
definitions:
  Example:
    type: object
    description: "Blah blah"
    additionalProperties:
      type: array
      example: blah
      items:
        type: string
```

**Comment by casualjim** [comment]
this spec is invalid

it should be:

```yaml
swagger: '2.0'
info:
  description: Example API service
  version: 1.0.0
  title: Example API
host: localhost
basePath: /v1
tags:
  - name: example
    description: Example API
schemes:
  - http
paths:
  '/example':
    get:
      tags:
        - example
      summary: summary
      description: description
      operationId: example
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/Example'
definitions:
  Example:
    type: object
    description: "Blah blah"
    additionalProperties:
      type: array
      example: blah
      items:
        type: string
```

**Comment by lestrrat** [comment]
Woohoo, a reply after 5 months! Yay.

For the record, I think it's totally fine that you pointed out the spec is wrong, but I don't think a go program should panic because of this. panic'ing in go is wrong. (of course, I haven't checked any recent version of go-swagger)
